# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
updates:
- package-ecosystem: cargo
  directory: "/common"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/bootx64"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/kernel"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/apps"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/page_box"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/syscalls"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/terminal"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/ralib"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/fs_server"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/frame_manager"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/message"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/pm"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/port_server"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: cargo
  directory: "/xhci"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
