[package]
name = "vm"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "vm"
crate-type = ["staticlib"]
test = false
bench = false

[dependencies]
linked_list_allocator = "0.9.1"
ralib = { path = "../../libs/ralib", default-features = false }
