[package]
name = "do_nothing"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "do_nothing"
test = false
bench = false

[lib]
test = false
bench = false

[dependencies]
ralib = { path = "../ralib" }

