[package]
name = "do_nothing"
version = "0.1.0"
edition = "2018"

[lib]
name = "do_nothing"
crate-type = ["staticlib"]
test = false
bench = false

[dependencies]
ralib = { path = "../ralib" }
syscalls = { path = "../syscalls" }

